language: objective-c
before_install:
  - gem install cocoapods
  - pod setup
  - pod install
before_script:
  - export LANG=en_US.UTF-8
script:
  - xctool -workspace freelancers.xcworkspace -scheme freelancers -sdk iphonesimulator7.0 ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace freelancers.xcworkspace -scheme freelancersTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
